# Generated by Django 5.1.7 on 2025-03-29 07:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_phone',
            field=models.CharField(max_length=15, unique=True, validators=[accounts.models.validate_number]),
        ),
    ]
